/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EsBackTop: typeof import('./src/components/ls-back-top/es-back-top.vue')['default']
    EsButton: typeof import('./src/components/ls-button/es-button.vue')['default']
    EsEmpty: typeof import('./src/components/ls-empty/es-empty.vue')['default']
    EsForm: typeof import('./src/components/ls-form/es-form.vue')['default']
    EsIcons: typeof import('./src/components/ls-icons/es-icons.vue')['default']
    EsList: typeof import('./src/components/ls-list/es-list.vue')['default']
    EsPage: typeof import('./src/components/ls-page/es-page.vue')['default']
    EsText: typeof import('./src/components/ls-text/es-text.vue')['default']
    EsUpload: typeof import('./src/components/ls-upload/es-upload.vue')['default']
  }
}
