export enum PromptsEnum {
  CREATED = '创建成功',
  DELETED = '删除成功',
  CLEARED = '清空成功',
  UPDATED = '修改成功',
  ENABLED = '启用成功',
  DISABLED = '禁用成功',
  ERROR_DELETE = '删除失败',
  ERROR_UPDATE = '修改失败',
  CONFIRM_CLEAR = '是否确认清空？清空后数据将无法恢复！',
  CONFIRM_DELETE = '是否确认删除？删除后数据将无法恢复！',
  CONFIRM_UPDATE = '是否确认修改？',
  CONFIRM_ENABLED = '是否确认启用？',
  CONFIRM_DISABLED = '是否确认禁用？',
  EMPTY_SELECTED = '请至少选择一项',
}
