/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EsCard: typeof import('./../components/es-card/es-card.vue')['default']
    EsEmpty: typeof import('./../components/es-empty/es-empty.vue')['default']
    EsIcons: typeof import('./../components/es-icons/es-icons.vue')['default']
    EsImage: typeof import('./../components/es-image/es-image.vue')['default']
    EsList: typeof import('./../components/es-list/es-list.vue')['default']
    EsNavBar: typeof import('./../components/es-nav-bar/es-nav-bar.vue')['default']
    EsPage: typeof import('./../components/es-page/es-page.vue')['default']
    EsSearch: typeof import('./../components/es-search/es-search.vue')['default']
    EsSwiper: typeof import('./../components/es-swiper/es-swiper.vue')['default']
    EsTabs: typeof import('./../components/es-tabs/es-tabs.vue')['default']
    EsText: typeof import('./../components/es-text/es-text.vue')['default']
  }
}
