/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EsIcons: typeof import('./../components/es-icons/es-icons.vue')['default']
    EsPage: typeof import('./../components/es-page/es-page.vue')['default']
    EsTabs: typeof import('./../components/es-tabs/es-tabs.vue')['default']
    UniIcons: typeof import('@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue')['default']
  }
}
