staticFile:
  dirs:
    default:
      prefix: '/'
      dir: '/public/'

    upload:
      prefix: '/'
      dir: '/public/upload/files/'

    clientPackage:
      prefix: '/'
      dir: '/public/clientPackage'
