prisma:
  # 是否格式化时间格式
  timeSerialize: true

  # 默认排除的字段
  exclude:
    - 'deletedAt'
    - 'password'

  # 单次列表查询的最大条数上线
  maxListItemLimit: 500

  # 分页列表的查询参数默认列表
  pagination:
    pageSize: 15
    pageIndex: 1
    orderBy:
