import {
  ComicReadRuleEnum,
  ComicSerialStatusEnum,
} from '../../modules/admin/work/comic/comic.constant'

export async function createInitialComics(prisma: any) {
  const initData = [
    {
      name: '进击的巨人',
      alias: 'Attack on Titan,進撃の巨人',
      cover: 'https://example.com/covers/attack-on-titan.jpg',
      popularity: 9500,
      popularityWeight: 1.2,
      language: 'ja',
      region: 'JP',
      ageRating: 'R15',
      isPublished: true,
      publishAt: new Date('2024-01-01'),
      lastUpdated: new Date(),
      description:
        '在这个世界上，人类居住在由三重巨大的城墙所围成的都市里。在城墙外面，有着似乎会捕食人类的巨人类生物「巨人」徘徊着，而唯一对外的通道只有各城墙上的门扉而已。',
      publisher: '讲谈社',
      originalSource: '官方授权',
      serialStatus: ComicSerialStatusEnum.COMPLETED,
      canDownload: true,
      canComment: true,
      readRule: ComicReadRuleEnum.FREE,
      purchaseAmount: null,
      totalChapters: 139,
      totalViews: 1500000,
      favoriteCount: 85000,
      commentCount: 12000,
      likeCount: 95000,
      rating: 9.2,
      ratingCount: 15000,
      seoTitle: '进击的巨人 - 热门漫画在线阅读',
      seoDescription:
        '进击的巨人是一部精彩的漫画作品，讲述了人类与巨人的战斗故事',
      seoKeywords: '进击的巨人,漫画,在线阅读,巨人',
      recommendWeight: 1.5,
      isRecommended: true,
      isHot: true,
      isNew: false,
      copyright: '© 諫山創・講談社',
      disclaimer: '本作品仅供娱乐，不代表任何立场',
      remark: '经典漫画作品，推荐首页展示',
    },
    {
      name: '海贼王',
      alias: 'One Piece,ワンピース',
      cover: 'https://example.com/covers/one-piece.jpg',
      popularity: 9800,
      popularityWeight: 1.3,
      language: 'ja',
      region: 'JP',
      ageRating: 'PG13',
      isPublished: true,
      publishAt: new Date('2024-01-01'),
      lastUpdated: new Date(),
      description:
        '拥有财富、名声、权力，这世界上的一切的男人 "海贼王" 哥尔·D·罗杰，在被行刑受死之前说了一句话，让全世界的人都涌向了大海。"想要我的宝藏吗？如果想要的话，那就到海上去找吧，我全部都放在那里。"',
      publisher: '集英社',
      originalSource: '官方授权',
      serialStatus: ComicSerialStatusEnum.SERIALIZING,
      canDownload: true,
      canComment: true,
      readRule: ComicReadRuleEnum.FREE,
      purchaseAmount: null,
      totalChapters: 1100,
      totalViews: 2000000,
      favoriteCount: 120000,
      commentCount: 18000,
      likeCount: 150000,
      rating: 9.5,
      ratingCount: 25000,
      seoTitle: '海贼王 - 热门漫画在线阅读',
      seoDescription: '海贼王是一部关于海盗冒险的精彩漫画作品',
      seoKeywords: '海贼王,漫画,在线阅读,冒险',
      recommendWeight: 1.8,
      isRecommended: true,
      isHot: true,
      isNew: false,
      copyright: '© 尾田栄一郎/集英社',
      disclaimer: '本作品仅供娱乐，不代表任何立场',
      remark: '超人气长篇漫画，必推作品',
    },
    {
      name: '鬼灭之刃',
      alias: 'Demon Slayer,鬼滅の刃',
      cover: 'https://example.com/covers/demon-slayer.jpg',
      popularity: 9200,
      popularityWeight: 1.1,
      language: 'ja',
      region: 'JP',
      ageRating: 'R15',
      isPublished: true,
      publishAt: new Date('2024-01-01'),
      lastUpdated: new Date(),
      description:
        '大正时代，卖炭少年炭治郎的平凡生活，在家人遭到鬼杀害的那一天发生剧变。唯一幸存但变成了鬼的妹妹祢豆子，以及追踪而来的鬼杀队剑士富冈义勇。',
      publisher: '集英社',
      originalSource: '官方授权',
      serialStatus: ComicSerialStatusEnum.COMPLETED,
      canDownload: true,
      canComment: true,
      readRule: ComicReadRuleEnum.FREE,
      purchaseAmount: null,
      totalChapters: 205,
      totalViews: 1200000,
      favoriteCount: 75000,
      commentCount: 9500,
      likeCount: 88000,
      rating: 9.0,
      ratingCount: 12000,
      seoTitle: '鬼灭之刃 - 热门漫画在线阅读',
      seoDescription: '鬼灭之刃是一部关于鬼杀队的精彩漫画作品',
      seoKeywords: '鬼灭之刃,漫画,在线阅读,鬼杀队',
      recommendWeight: 1.3,
      isRecommended: true,
      isHot: true,
      isNew: false,
      copyright: '© 吾峠呼世晴/集英社',
      disclaimer: '本作品仅供娱乐，不代表任何立场',
      remark: '现象级漫画作品，强烈推荐',
    },
    {
      name: '你的名字',
      alias: 'Your Name,君の名は',
      cover: 'https://example.com/covers/your-name.jpg',
      popularity: 8500,
      popularityWeight: 1.0,
      language: 'ja',
      region: 'JP',
      ageRating: 'PG',
      isPublished: true,
      publishAt: new Date('2024-01-01'),
      lastUpdated: new Date(),
      description:
        '住在日本乡下的女高中生宫水三叶，和住在东京的男高中生立花泰树，两人在梦中交换了身体。起初以为只是奇怪的梦，但逐渐意识到彼此确实在交换身体...',
      publisher: 'KADOKAWA',
      originalSource: '官方授权',
      serialStatus: ComicSerialStatusEnum.COMPLETED,
      canDownload: true,
      canComment: true,
      readRule: ComicReadRuleEnum.PAID,
      purchaseAmount: 500,
      totalChapters: 3,
      totalViews: 450000,
      favoriteCount: 35000,
      commentCount: 2800,
      likeCount: 42000,
      rating: 8.8,
      ratingCount: 5500,
      seoTitle: '你的名字 - 热门漫画在线阅读',
      seoDescription: '你的名字是一部温馨的青春恋爱漫画作品',
      seoKeywords: '你的名字,漫画,在线阅读,青春,恋爱',
      recommendWeight: 1.0,
      isRecommended: false,
      isHot: false,
      isNew: true,
      copyright: '© 新海誠/KADOKAWA',
      disclaimer: '本作品仅供娱乐，不代表任何立场',
      remark: '温馨治愈系作品，适合青少年阅读',
    },
    {
      name: '龙珠',
      alias: 'Dragon Ball,ドラゴンボール',
      cover: 'https://example.com/covers/dragon-ball.jpg',
      popularity: 9000,
      popularityWeight: 1.4,
      language: 'ja',
      region: 'JP',
      ageRating: 'PG13',
      isPublished: true,
      publishAt: new Date('2024-01-01'),
      lastUpdated: new Date(),
      description:
        '在很久很久以前，有一个叫做孙悟空的少年，他拥有着惊人的力量和纯真的心灵。为了寻找传说中的龙珠，他踏上了冒险的旅程...',
      publisher: '集英社',
      originalSource: '官方授权',
      serialStatus: ComicSerialStatusEnum.COMPLETED,
      canDownload: true,
      canComment: true,
      readRule: ComicReadRuleEnum.FREE,
      purchaseAmount: null,
      totalChapters: 519,
      totalViews: 1800000,
      favoriteCount: 95000,
      commentCount: 15000,
      likeCount: 125000,
      rating: 9.3,
      ratingCount: 20000,
      seoTitle: '龙珠 - 经典漫画在线阅读',
      seoDescription: '龙珠是一部经典的热血冒险漫画作品',
      seoKeywords: '龙珠,漫画,在线阅读,热血,冒险',
      recommendWeight: 1.6,
      isRecommended: true,
      isHot: false,
      isNew: false,
      copyright: '© 鳥山明/集英社',
      disclaimer: '本作品仅供娱乐，不代表任何立场',
      remark: '经典热血漫画，影响深远',
    },
  ]

  for (const item of initData) {
    // 先查找是否已存在同名漫画
    const existingComic = await prisma.workComic.findFirst({
      where: { name: item.name },
    })

    if (!existingComic) {
      // 如果不存在，则创建新记录
      await prisma.workComic.create({
        data: item,
      })
    } else {
      // 如果已存在，则更新记录
      await prisma.workComic.update({
        where: { id: existingComic.id },
        data: item,
      })
    }
  }

  console.log('✅ 漫画种子数据创建完成')
}
